kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-master-volume
  labels:
    type: local
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/postgres/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker03
